#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# Appliance Manual RAG — automated server deployment
#
# Installs:  system deps, Ollama, Hermes 3, nomic-embed-text, Python venv,
#            Node deps, two systemd services, and an Nginx reverse proxy.
#
# Idempotent: safe to re-run after a server reboot or to pick up new code.
#
# Usage:    sudo ./deploy.sh
# ──────────────────────────────────────────────────────────────────────────────

set -euo pipefail

# ─── Configurable ─────────────────────────────────────────────────────────────
APP_USER="${APP_USER:-rag}"
APP_DIR="${APP_DIR:-/opt/appliance-rag}"
OLLAMA_LLM_MODEL="${OLLAMA_LLM_MODEL:-hermes3}"
OLLAMA_EMBED_MODEL="${OLLAMA_EMBED_MODEL:-nomic-embed-text}"
BACKEND_PORT="${BACKEND_PORT:-8000}"
FRONTEND_PORT="${FRONTEND_PORT:-3000}"
NGINX_PORT="${NGINX_PORT:-80}"
PUBLIC_HOSTNAME="${PUBLIC_HOSTNAME:-}"   # blank = use LAN IP

# ─── Colors ──────────────────────────────────────────────────────────────────
BOLD=$'\033[1m'; DIM=$'\033[2m'; RESET=$'\033[0m'
RED=$'\033[31m'; GRN=$'\033[32m'; YEL=$'\033[33m'; CYN=$'\033[36m'
step() { printf "\n${BOLD}${CYN}==> %s${RESET}\n" "$*"; }
ok()   { printf "${GRN}✓${RESET} %s\n" "$*"; }
warn() { printf "${YEL}!${RESET} %s\n" "$*"; }
die()  { printf "${RED}✗ %s${RESET}\n" "$*" >&2; exit 1; }

# ─── Root check ───────────────────────────────────────────────────────────────
[[ $EUID -eq 0 ]] || die "Re-run with sudo: sudo ./deploy.sh"

# ─── Detect distro ───────────────────────────────────────────────────────────
. /etc/os-release 2>/dev/null || true
DISTRO="${ID:-ubuntu}"
case "$DISTRO" in
    ubuntu|debian|pop|linuxmint) PKG=apt ;;
    centos|rhel|rocky|almalinux|fedora) PKG=dnf ;;
    arch|manjaro) PKG=pacman ;;
    *) die "Unsupported distro: $DISTRO. Install manually." ;;
esac
ok "Detected distro: $DISTRO (using $PKG)"

# ─── 1. System packages ──────────────────────────────────────────────────────
step "Installing system packages…"
case "$PKG" in
    apt)
        export DEBIAN_FRONTEND=noninteractive
        apt-get update -y
        apt-get install -y python3 python3-venv python3-pip nodejs npm nginx curl ufw
        ;;
    dnf)
        dnf install -y python3 python3-pip nodejs npm nginx curl firewalld
        ;;
    pacman)
        pacman -Sy --noconfirm python nodejs npm nginx curl ufw
        ;;
esac
ok "System packages installed"

# ─── 2. Install Ollama if missing ─────────────────────────────────────────────
step "Checking for Ollama…"
if ! command -v ollama >/dev/null 2>&1; then
    warn "Ollama not found — installing"
    curl -fsSL https://ollama.com/install.sh | sh
    ok "Ollama installed"
else
    ok "Ollama already present"
fi

systemctl enable ollama.service 2>/dev/null || true
systemctl start  ollama.service 2>/dev/null || true
for i in {1..30}; do
    curl -fsS -m 2 http://localhost:11434/api/tags >/dev/null 2>&1 && break
    sleep 1
done
curl -fsS -m 2 http://localhost:11434/api/tags >/dev/null 2>&1 \
    || die "Ollama failed to start. Check: journalctl -u ollama"
ok "Ollama is running"

# ─── 3. Pull models ───────────────────────────────────────────────────────────
step "Pulling Ollama models…"
ollama pull "$OLLAMA_LLM_MODEL"
ollama pull "$OLLAMA_EMBED_MODEL"
ok "Models pulled: $OLLAMA_LLM_MODEL, $OLLAMA_EMBED_MODEL"

# ─── 4. Application user + directory ─────────────────────────────────────────
step "Setting up application user and directory…"
if ! id "$APP_USER" >/dev/null 2>&1; then
    useradd --system --create-home --shell /bin/bash "$APP_USER"
    ok "Created user $APP_USER"
else
    ok "User $APP_USER already exists"
fi

mkdir -p "$APP_DIR"
cp -a . "$APP_DIR/"
chown -R "$APP_USER":"$APP_USER" "$APP_DIR"
ok "App installed to $APP_DIR"

# ─── 5. Python venv + deps ───────────────────────────────────────────────────
step "Installing Python dependencies…"
sudo -u "$APP_USER" bash -c "
    cd '$APP_DIR/backend'
    python3 -m venv venv
    source venv/bin/activate
    pip install --quiet --upgrade pip
    pip install --quiet -r requirements.txt
"
ok "Python dependencies installed"

# ─── 6. .env file ─────────────────────────────────────────────────────────────
step "Writing backend .env…"
cat > "$APP_DIR/backend/.env" <<EOF
# Generated by deploy.sh on $(date -Iseconds)
BACKEND_HOST=127.0.0.1
BACKEND_PORT=$BACKEND_PORT
OLLAMA_BASE_URL=http://localhost:11434
OLLAMA_LLM_MODEL=$OLLAMA_LLM_MODEL
OLLAMA_EMBED_MODEL=$OLLAMA_EMBED_MODEL
OLLAMA_REQUEST_TIMEOUT=360
DOCS_DIR=../data/documents
STORAGE_DIR=../data/storage
ALLOWED_ORIGINS=http://localhost,http://localhost:$NGINX_PORT
EOF
chown "$APP_USER":"$APP_USER" "$APP_DIR/backend/.env"
ok ".env written"

# Ensure data directories exist
mkdir -p "$APP_DIR/data/documents" "$APP_DIR/data/storage" "$APP_DIR/data/logs"
chown -R "$APP_USER":"$APP_USER" "$APP_DIR/data"

# ─── 7. Frontend deps + production build ──────────────────────────────────────
step "Installing + building frontend…"
sudo -u "$APP_USER" bash -c "
    cd '$APP_DIR/frontend'
    npm install --no-audit --no-fund --loglevel=error
    NEXT_PUBLIC_API_URL= npm run build
"
ok "Frontend built"

# ─── 8. systemd services ─────────────────────────────────────────────────────
step "Installing systemd services…"

cat > /etc/systemd/system/appliance-rag-backend.service <<EOF
[Unit]
Description=Appliance Manual RAG — FastAPI backend
After=network.target ollama.service
Wants=ollama.service

[Service]
Type=simple
User=$APP_USER
WorkingDirectory=$APP_DIR/backend
EnvironmentFile=$APP_DIR/backend/.env
ExecStart=$APP_DIR/backend/venv/bin/python -m uvicorn app.main:app --host 127.0.0.1 --port $BACKEND_PORT
Restart=on-failure
RestartSec=5
StandardOutput=append:$APP_DIR/data/logs/backend.log
StandardError=append:$APP_DIR/data/logs/backend.log

[Install]
WantedBy=multi-user.target
EOF

cat > /etc/systemd/system/appliance-rag-frontend.service <<EOF
[Unit]
Description=Appliance Manual RAG — Next.js frontend
After=network.target appliance-rag-backend.service

[Service]
Type=simple
User=$APP_USER
WorkingDirectory=$APP_DIR/frontend
Environment=PORT=$FRONTEND_PORT
Environment=HOSTNAME=127.0.0.1
Environment=NEXT_PUBLIC_API_URL=
ExecStart=$APP_DIR/frontend/node_modules/.bin/next start --port $FRONTEND_PORT
Restart=on-failure
RestartSec=5
StandardOutput=append:$APP_DIR/data/logs/frontend.log
StandardError=append:$APP_DIR/data/logs/frontend.log

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable appliance-rag-backend.service appliance-rag-frontend.service
systemctl restart appliance-rag-backend.service appliance-rag-frontend.service
ok "systemd services installed and started"

for i in {1..30}; do
    curl -fsS -m 2 "http://localhost:$BACKEND_PORT/health" >/dev/null 2>&1 && break
    sleep 1
done

# ─── 9. Nginx reverse proxy ───────────────────────────────────────────────────
step "Configuring Nginx…"
cp "$APP_DIR/infrastructure/nginx.conf" /etc/nginx/sites-available/appliance-rag || true
cat > /etc/nginx/sites-available/appliance-rag <<EOF
server {
    listen $NGINX_PORT default_server;
    listen [::]:$NGINX_PORT default_server;
    server_name _;

    client_max_body_size 100M;   # allow large PDF uploads

    gzip on;
    gzip_types text/plain text/css application/json application/javascript;

    location /api/ {
        rewrite ^/api/(.*)$ /\$1 break;
        proxy_pass         http://127.0.0.1:$BACKEND_PORT;
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_read_timeout 600s;
        proxy_send_timeout 600s;
    }

    location / {
        proxy_pass         http://127.0.0.1:$FRONTEND_PORT;
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade           \$http_upgrade;
        proxy_set_header   Connection        "upgrade";
    }
}
EOF

ln -sf /etc/nginx/sites-available/appliance-rag /etc/nginx/sites-enabled/appliance-rag
rm -f /etc/nginx/sites-enabled/default
nginx -t && systemctl reload nginx
ok "Nginx configured and reloaded"

# ─── 10. Firewall ─────────────────────────────────────────────────────────────
step "Opening firewall…"
if command -v ufw >/dev/null 2>&1; then
    ufw allow "$NGINX_PORT"/tcp || true
    ufw --force enable || true
    ok "ufw: opened port $NGINX_PORT"
elif command -v firewall-cmd >/dev/null 2>&1; then
    firewall-cmd --permanent --add-port="$NGINX_PORT/tcp" || true
    firewall-cmd --reload || true
    ok "firewalld: opened port $NGINX_PORT"
else
    warn "No firewall tool found. Open port $NGINX_PORT manually."
fi

# ─── Done! Print summary ──────────────────────────────────────────────────────
LAN_IP=$(hostname -I 2>/dev/null | awk '{print $1}')
[[ -z "$LAN_IP" ]] && LAN_IP=$(ip -4 addr show scope global 2>/dev/null | awk '/inet/ {print $2}' | cut -d/ -f1 | head -1)

printf "\n${BOLD}${GRN}🎉 Deployment complete!${RESET}\n"
printf "  Local URL:    ${CYN}http://localhost${RESET}\n"
[[ -n "$LAN_IP" ]] && printf "  LAN URL:      ${CYN}http://%s${RESET}\n" "$LAN_IP"
[[ -n "$PUBLIC_HOSTNAME" ]] && printf "  Public URL:   ${CYN}http://%s${RESET}\n" "$PUBLIC_HOSTNAME"

printf "\n${BOLD}Manage the services:${RESET}\n"
printf "  ${DIM}sudo systemctl status appliance-rag-backend${RESET}\n"
printf "  ${DIM}sudo systemctl status appliance-rag-frontend${RESET}\n"
printf "  ${DIM}sudo journalctl -u appliance-rag-backend -f${RESET}\n"
printf "\n${BOLD}Update the app:${RESET}\n"
printf "  cd %s && sudo git pull && sudo ./deploy.sh\n" "$APP_DIR"
